# Generated by Django 5.0.4 on 2024-07-21 21:16

from django.db import migrations, models
import json

def convert_bytea_to_jsonb(apps, schema_editor):
    Pedido = apps.get_model('pedidos', 'Pedido')
    for pedido in Pedido.objects.all():
        if pedido.evidencia_pago:
            try:
                # Convierte el campo bytea a JSON si es posible
                data = json.loads(pedido.evidencia_pago.tobytes().decode('utf-8'))
                pedido.evidencia_pago = data
                pedido.save()
            except Exception as e:
                print(f"Error converting evidencia_pago: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0020_pedido_productos_pedido_servicios'),  # Ajusta esta dependencia según tu caso
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='evidencia_pago_temp',
            field=models.JSONField(null=True, blank=True),
        ),
        migrations.RunPython(convert_bytea_to_jsonb),
        migrations.RemoveField(
            model_name='pedido',
            name='evidencia_pago',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='evidencia_pago_temp',
            new_name='evidencia_pago',
        ),
    ]
